language: java
jdk: openjdk10
addons:
  apt:
    packages:
      ant
before_script:
   - mkdir ./lib
   - wget "https://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar" -O lib/junit-4.12.jar
   - wget "https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" -O lib/hamcrest-core-1.3.jar
   - sudo apt-get install ant-optional
script: ant test
